@ModularMonolith.Web_HostAddress = http://localhost:5294

GET {{ModularMonolith.Web_HostAddress}}/module1
Accept: application/json
###

@ModuleId=04069dc5-c48e-4171-8828-32dd98b074b0
GET {{ModularMonolith.Web_HostAddress}}/module1/{{ModuleId}}
Accept: application/json

###

POST {{ModularMonolith.Web_HostAddress}}/module1
Accept: application/json
Content-Type: application/json

{
  "Id": "30f8e749-6234-4483-b5a1-cdddb30884c5",
  "Name": "HELLO",
  "Value": 52
}

###

DELETE {{ModularMonolith.Web_HostAddress}}/module1/30f8e749-6234-4483-b5a1-cdddb30884c5
Accept: application/json

###

POST {{ModularMonolith.Web_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email": "test@test.test",
  "password": "Testtest1@"
}

###

POST {{ModularMonolith.Web_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
"email": "test@test.test",
"password": "Testtest1@"
}
###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJ0ZXN0QHRlc3QudGVzdCIsImlhdCI6MTcxMDY2NDg3OCwiZXhwIjoxNzEwNjY4NDc4LCJuYmYiOjE3MTA2NjQ4Nzh9.6bo7t9HHCRNH6heb5v_OY-ujc2Y6cbPfAwj5NNheM58

POST {{ModularMonolith.Web_HostAddress}}/cart
Accept: text/plain
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "module1Id": "04069dc5-c48e-4171-8828-32dd98b074b0",
  "name": "Test",
  "value": 1
}

###

GET {{ModularMonolith.Web_HostAddress}}/cart
Accept: application/json
Authorization: Bearer {{token}}

###